# Build the accessibility DLL WITH debug keys (F1-F12 / number keys), gated by chaos.dat.
# Self-contained: if the matched chaos.dat + chaos_hash.h are missing, it generates
# them here (the SHA-256 is baked into the DLL automatically), then builds with
# ENABLE_DEBUG_KEYS. Delete chaos.dat to rotate the gate file.
# Output: x64\Release\xinput1_4.dll + src\cpp\chaos.dat — deploy BOTH together.
$datPath = Join-Path $PSScriptRoot "..\src\cpp\chaos.dat"
$hdrPath = Join-Path $PSScriptRoot "..\src\cpp\chaos_hash.h"

if (-not (Test-Path $datPath) -or -not (Test-Path $hdrPath)) {
    Write-Host "Generating matched chaos.dat + chaos_hash.h..."
    $key  = [Text.Encoding]::ASCII.GetBytes("HADES_ACCESSIBILITY_DEBUG_KEY_GATE_FILE_VALIDATION_v001")
    $data = New-Object byte[] 8192
    [Array]::Copy($key, $data, $key.Length)
    $rand = New-Object byte[] (8192 - $key.Length)
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($rand)
    [Array]::Copy($rand, 0, $data, $key.Length, $rand.Length)
    [IO.File]::WriteAllBytes($datPath, $data)

    $sha = [Security.Cryptography.SHA256]::Create().ComputeHash($data)
    $hdr = @(
        "#pragma once"
        "// Generated by build-debug.ps1 - DO NOT EDIT. SHA-256 of the matching"
        "// chaos.dat gate file. Delete chaos.dat to rotate."
        "static const unsigned char CHAOS_HASH[32] = {"
    )
    for ($i = 0; $i -lt 32; $i += 8) {
        $hdr += "    " + (($sha[$i..($i + 7)] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ','
    }
    $hdr += "};"
    Set-Content -Path $hdrPath -Value $hdr -Encoding ASCII
}

Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Enter-VsDevShell -VsInstallPath "C:\Program Files\Microsoft Visual Studio\2022\Community" -DevCmdArguments "-arch=amd64" -SkipAutomaticLocation | Out-Null
msbuild "$PSScriptRoot\..\src\cpp\hades.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:ExtraDefines=ENABLE_DEBUG_KEYS /t:Build /verbosity:minimal

Write-Host ""
Write-Host "Debug build complete. Deploy BOTH to the game's x64\ folder (matched pair):" -ForegroundColor Yellow
Write-Host "  - x64\Release\xinput1_4.dll"
Write-Host "  - src\cpp\chaos.dat"
