#!/usr/bin/env python3
"""
Generate subtitles/{lang}.lua files from the game's Subtitles CSV files.

Each CSV file maps voice cue IDs to subtitle text. Format:
    Status,Prefix,Number,FullID,,,,Text,,,Notes

Output: Lua files with SubtitleData table mapping cue IDs to text strings.
These are loaded at runtime by the C++ layer alongside language files.

Usage:
    python generate_subtitles.py
"""

import csv
import os
import sys
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "subtitles")

# Try to find the game's Subtitles directory
GAME_PATHS = [
    r"C:\Program Files (x86)\Steam\steamapps\common\Hades\Content\Subtitles",
    r"D:\Steam\steamapps\common\Hades\Content\Subtitles",
    r"C:\Steam\steamapps\common\Hades\Content\Subtitles",
]

LANGS = ["en", "de", "es", "fr", "it", "ja", "ko", "pl", "pt-BR", "ru", "zh-CN"]


def find_subtitles_dir():
    for p in GAME_PATHS:
        if os.path.isdir(p):
            return p
    return None


def parse_csv_file(filepath):
    """Parse a subtitle CSV file, returning dict of cue_id -> text."""
    entries = {}
    with open(filepath, 'r', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 8:
                continue
            status = row[0].strip()
            cue_id = row[3].strip()
            text = row[7].strip()
            # Skip header rows, unused lines, and empty text
            if not cue_id or not text:
                continue
            if cue_id == "ID" or status == "Unused":
                continue
            # Remove surrounding quotes if present
            if text.startswith('"') and text.endswith('"'):
                text = text[1:-1]
            entries[cue_id] = text
    return entries


def escape_lua_string(s):
    """Escape a string for Lua double-quoted string literal."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '')
    return s


def generate_lua_file(entries, lang, output_path):
    """Generate a Lua file with SubtitleData table."""
    lines = []
    lines.append("-- Auto-generated subtitle data for language: %s" % lang)
    lines.append("-- Generated by generate_subtitles.py")
    lines.append("-- %d entries" % len(entries))
    lines.append("")
    lines.append("SubtitleData = {")
    for cue_id in sorted(entries.keys()):
        text = entries[cue_id]
        lines.append('    ["%s"] = "%s",' % (escape_lua_string(cue_id), escape_lua_string(text)))
    lines.append("}")
    lines.append("")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return len(entries)


def main():
    subtitles_dir = find_subtitles_dir()
    if not subtitles_dir:
        print("ERROR: Could not find game's Subtitles directory.")
        print("Tried:", GAME_PATHS)
        sys.exit(1)

    print("Subtitles source: %s" % subtitles_dir)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for lang in LANGS:
        lang_dir = os.path.join(subtitles_dir, lang)
        if not os.path.isdir(lang_dir):
            print("  %s: SKIPPED (directory not found)" % lang)
            continue

        # Parse all CSV files for this language
        all_entries = {}
        csv_files = sorted(glob.glob(os.path.join(lang_dir, "*.csv")))
        for csv_file in csv_files:
            entries = parse_csv_file(csv_file)
            all_entries.update(entries)

        # Generate Lua file
        output_path = os.path.join(OUTPUT_DIR, "%s.lua" % lang)
        count = generate_lua_file(all_entries, lang, output_path)
        size_kb = os.path.getsize(output_path) / 1024
        print("  %s.lua: %d entries (%.1f KB)" % (lang, count, size_kb))

    print("\nGenerated subtitle files in %s" % OUTPUT_DIR)
    print("Deploy subtitles/ folder to game's x64/ directory.")


if __name__ == "__main__":
    main()
