#!/usr/bin/env python3
"""
Generate hades/embedded_helptext.cpp from the game's HelpText.en.sjson — an
id -> on-screen-display-text lookup the engine-menu reader uses to resolve
labels that aren't stored in the component (e.g. the God Mode toggle keeps the
internal id "EasyMode" but the screen shows "God Mode").

Only static menu-screen labels are kept (entries whose Id looks menu-related and
whose DisplayName has no runtime {$...} template). Display formatting (@icons,
{#format}, {!icons}) is stripped.
"""
import os
import re

HT = r"C:\Program Files (x86)\Steam\steamapps\common\Hades\Content\Game\Text\en\HelpText.en.sjson"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "cpp", "embedded_helptext.cpp")

# Keep ids relevant to the engine menus (the screens engine_menu hooks) + a few
# generic shell/button ids. Generous prefix list; harmless extras are fine since
# only menu components' ids are ever looked up.
KEEP = re.compile(
    r'(Screen|Dialog|Menu|Settings|Controls|KeyMapping|Resolution|Language|'
    r'Profile|LoadSave|CloudSave|Shell|Announcement|PatchNotes|About|Launch|'
    r'Exit|Confirm|Vibration|Subtitle|Brightness|Volume|EasyMode|HardMode|'
    r'FullScreen|Windowed|Cursor|DeadZone|AimAssist|Rumble)', re.IGNORECASE)


def clean(s):
    s = re.sub(r'@\S+', '', s)            # asset/icon refs like @GUI\Shell\EasyMode
    s = re.sub(r'\{[^}]*\}', '', s)       # {#Format}, {!Icons.X}, {SL} button tokens, etc.
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def main():
    text = open(HT, encoding='utf-8').read()
    entries = {}
    cur = None
    for line in text.splitlines():
        m = re.search(r'\bId\s*=\s*"([^"]+)"', line)
        if m:
            cur = m.group(1)
            continue
        m = re.search(r'\bDisplayName\s*=\s*"(.*)"\s*$', line)
        if m and cur:
            dn = m.group(1)
            if '{$' not in dn and KEEP.search(cur):   # static label, menu-relevant
                c = clean(dn)
                if c and all(32 <= ord(ch) < 127 for ch in c):   # plain ASCII labels
                    entries[cur] = c
            cur = None

    items = sorted(entries.items())   # ASCII -> matches C++ strcmp ordering

    def esc(s):
        return s.replace('\\', '\\\\').replace('"', '\\"')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// AUTO-GENERATED by generate_helptext.py - do not edit.\n')
        f.write('// id -> on-screen text, from HelpText.en.sjson. Sorted for binary search.\n')
        f.write('#include "embedded_helptext.h"\n#include <cstring>\n\n')
        f.write('namespace {\nstruct HelpEntry { const char* id; const char* text; };\n')
        f.write('static const HelpEntry kEntries[] = {\n')
        for k, v in items:
            f.write(f'    {{ "{esc(k)}", "{esc(v)}" }},\n')
        f.write('};\n')
        f.write(f'static const int kCount = {len(items)};\n}}  // namespace\n\n')
        f.write('const char* HelpText::Lookup(const char* id)\n{\n')
        f.write('    int lo = 0, hi = kCount - 1;\n')
        f.write('    while (lo <= hi) {\n')
        f.write('        int mid = (lo + hi) / 2;\n')
        f.write('        int c = strcmp(id, kEntries[mid].id);\n')
        f.write('        if (c == 0) return kEntries[mid].text;\n')
        f.write('        if (c < 0) hi = mid - 1; else lo = mid + 1;\n')
        f.write('    }\n    return nullptr;\n}\n')

    print(f"Wrote {OUT}: {len(items)} entries ({os.path.getsize(OUT)} bytes)")
    for k in ("MiscSettingsScreen_EasyModeLabel", "MainMenuScreen_Settings"):
        print(f"  {k} -> {entries.get(k)!r}")


if __name__ == "__main__":
    main()
